### ISSUE TITLE
SetUserAdvancedDetails and Diet for user.

### ISSUE THREAD

**Issue by jiacheng-hou** [smcAdvJavaGrp2/MealGuru#20]
Now the SetUserAdvancedDetails pane is still empty, so I guess I can use it to set Diet for user. User can set their daily intake goals for calories etc. Then I will try to make the database to save these info, I might need help on that.

**Comment by JKeirans** [comment]
Try to assign out tasks or nothing will get done.

**Comment by jscul** [comment]
Saving that stuff will be easy. I can do that in 20 minutes. Nihal said there isn't really a point in having preferences for everything though... we can try to see if he'd want to update all his graphs, I know he has a final tomorrow.

What nutritional values do you guys want to have goal amounts for? Calories? Protein? Fat? I can save as many as you need.

**Comment by jiacheng-hou** [comment]
Check the Diet class in the new branch issue #20. Currently it has every nutritional value that a food has and a categoryPreference to match the tags that a food has.

If you could do the database thing that would be really helpful. I'm currently doing the gui.

Also if we complete the diet, the guru will have some new functions as well.

**Comment by jscul** [comment]
Everything should be updated for you...

**new DietDA().saveDiet(Diet diet);** //saves a diet for the active user _(should only use once in acc creation)_
**new DietDA().updateDiet(Diet diet);** //updates the diet of the active user

**new DietDA().getDiet();** //returns a Diet object given whoever the active user is...

Let me know if you need anything else.

Where will we update the preferences?

**Comment by jscul** [comment]
Actually, let me know if you need categories or something saved... I didn't put that in, I'm not sure what we'd do with that.

**Comment by jiacheng-hou** [comment]
Something wrong with the database, probably need another table for Diet in database.

```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: Diet)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
	at data.mealguru.DietDA.updateDiet(DietDA.java:124)
	at gui.UserEditor.lambda$5(UserEditor.java:233)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by JKeirans** [comment]
Open the db with:

http://sqlitebrowser.org/

Create a new table, then create a schema according to what you want to save in your diet db. 
Honestly you don't even need to know how schemas work to copy the syntax

Also beautifully designed code, and doesn't matter, but semantically confusing method name here:
I won't change it while you are doing db stuff but you might want to when you push your work to master.
JDBC.java  
getMysqlConnection();

should be :
getSqliteConnection();

**Comment by jscul** [comment]
The table should have been made already... if you download the DB there's a diet table already in it.

CREATE TABLE `Diet` (
	`id`	INTEGER,
	`user_id`	INT NOT NULL,
	`caloric_goal`	INT,
	`total_fat`	VARCHAR(16),
	`saturated_fat`	VARCHAR(16),
	`trans_fat`	VARCHAR(16),
	`cholesterol`	VARCHAR(16),
	`sodium`	VARCHAR(16),
	`carbohydrates`	VARCHAR(16),
	`dietary_fiber`	VARCHAR(16),
	`sugar`	VARCHAR(16),
	`protein`	VARCHAR(16),
	`vitamin_a_goal`	INT,
	`vitamin_c_goal`	INT,
	`iron_goal`	INT,
	`calcium_goal`	INT,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`user_id`) REFERENCES `User`(`user_id`)
);

I'm not sure... but I think we have trouble with the DB being pushed and pulled/compared to the master.
